=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/package.dtd
<!-- Root fileElement -->
<!ELEMENT root (projectActionList*) >
   <!ATTLIST root version CDATA #REQUIRED >
 
<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList (applyWhen|projectActionList|projectActionListRef|variable|block|excludeSourceFile|excludeSourceFolder|createFolder|copy|projectOption|customAction)*>
   <!ATTLIST projectActionList id    ID     #IMPLIED>
   <!ATTLIST projectActionList root  CDATA  #IMPLIED>

<!-- Condition controlling when list action is applied -->
<!ELEMENT applyWhen (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)>

<!ELEMENT and ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)*) >
<!ELEMENT or  ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)*) >
<!ELEMENT not  (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches) >

<!ELEMENT variableRef EMPTY >
   <!ATTLIST variableRef idRef 			CDATA 			#REQUIRED>
   <!ATTLIST variableRef condition 		(isTrue|lessThan|lessThanOrEqual|equal|greaterThan|greaterThanOrEqual) "isTrue">
   <!ATTLIST variableRef defaultValue 	(true|false) 	#IMPLIED>
   <!ATTLIST variableRef value   		CDATA 			#IMPLIED>

<!ELEMENT deviceNameIs (#PCDATA) >
<!ELEMENT deviceFamilyIs (#PCDATA) >
<!ELEMENT deviceSubfamilyIs (#PCDATA) >
<!ELEMENT deviceNameMatches (#PCDATA) >
<!ELEMENT deviceFamilyMatches (#PCDATA) >
<!ELEMENT deviceSubfamilyMatches (#PCDATA) >

<!ELEMENT projectActionListRef EMPTY>
   <!ATTLIST projectActionListRef ref IDREF #REQUIRED>
 
<!-- Variable controlling a block -->
<!ELEMENT variable ((requirement|preclusion)*) >
   <!ATTLIST variable id           CDATA #REQUIRED>
   <!ATTLIST variable name         CDATA #IMPLIED>
   <!ATTLIST variable description  CDATA #IMPLIED>
   <!ATTLIST variable type         (boolean) 	"boolean" >
   <!ATTLIST variable defaultValue (true|false) "false">
   <!ATTLIST variable values       CDATA #IMPLIED>
   
<!ELEMENT requirement EMPTY >
   <!ATTLIST requirement idRef CDATA #REQUIRED>

<!ELEMENT preclusion EMPTY >
   <!ATTLIST preclusion idRef CDATA #REQUIRED>

<!-- Condition controlling actions -->
<!ELEMENT block (applyWhen,(excludeSourceFile|excludeSourceFolder|createFolder|copy|deleteResource|projectOption|customAction)*)>
   <!--ATTLIST block variable    IDREF  #REQUIRED -->
   <!--ATTLIST block negated     (true|false) "false" -->
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    CDATA #REQUIRED>

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source  				CDATA #REQUIRED>
   <!ATTLIST copy target  				CDATA #REQUIRED>
   <!ATTLIST copy type    				CDATA #IMPLIED>
   <!ATTLIST copy macroReplacement  (true|false) "true">
   <!ATTLIST copy replace           (true|false) "false">
   
<!-- Eclipse project options (for gcc, gdb etc) -->
<!ELEMENT projectOption (value*)>
   <!ATTLIST projectOption id        CDATA        #REQUIRED>
   <!ATTLIST projectOption replace   (true|false) "false">

<!-- Custom build action -->
<!ELEMENT customAction (value)* >
   <!ATTLIST customAction class       CDATA #REQUIRED>
   
<!-- Attribute value for projectOption --> 
<!ELEMENT value (#PCDATA)>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKLxxZ4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MK1x MKL2x MKL3x -->
   <projectActionList id="Options-file-list-MKLxxZ4">
      <applyWhen>
         <or>
            <deviceSubfamilyIs>MKL14Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL15Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL16Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL24Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL25Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL26Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL34Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL36Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL46Z4</deviceSubfamilyIs>
         </or>
      </applyWhen>
      <variable id="Clock-setup-MKL25" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="UART-setup-MKL25" name="UART setup code" description="Adds C stdio (UART) support for newlib" />
      <condition variable="Clock-setup-MKL25">
         <copy source="Startup_Code/clock-MKLxx.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKLxx.h" target="Project_Headers/clock_configure.h" />
      </condition>
      <condition variable="UART-setup-MKL25">
         <copy source="Startup_Code/uart-mkl.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </condition>
   </projectActionList>
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.CFV1_DeviceOptions/Options-file-list-CFV1Plus.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >
   <!-- Extra Optional files for Coldfire V1+ -->
   <projectActionList id="Options-file-list-CFV1Plus" >
      <applyWhen>
         <deviceFamilyIs>CFV1Plus</deviceFamilyIs>
      </applyWhen>
      <variable id="projectOptionValue.Clock-setup" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="projectOptionValue.UART-setup" name="UART setup code" description="Adds C stdio (UART) support for newlib">
         <requirement idRef="projectOptionValue.Clock-setup"/>
      </variable>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-cfv1plus.c"                   target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-cfv1plus.h"      target="Project_Headers/clock_configure.h" />
      </block>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/uart.c"                         target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h"                      target="Project_Headers/uart.h" />
         <copy source="Sources/main-uart.c"                         target="Sources/main.c" replace="true"/>
      </block>
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKxxM10Z.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKxx10Z -->
   <projectActionList id="Options-file-list-MKxxM10Z">
      <applyWhen>
         <or>
            <deviceSubfamilyIs>MK10DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK20DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK30DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK40DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK50DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK51DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK52DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK53DZ10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK60DZ10</deviceSubfamilyIs>
         </or>
      </applyWhen>
      <variable id="projectOptionValue.Clock-setup" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="projectOptionValue.UART-setup" name="UART setup code" description="Adds C stdio (UART) support for newlib" >
         <requirement idRef="projectOptionValue.Clock-setup"/>
      </variable>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-MKxxZ.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKxxM10Z.h" target="Project_Headers/clock_configure.h" />
      </block>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/uart-mk.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </block>
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKE0xZ4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKE04, MKE06 -->
   <projectActionList id="Options-file-list-MKE0xZ4">
      <applyWhen>
         <or>
            <deviceSubfamilyIs>MKE04Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKE06Z4</deviceSubfamilyIs>
	      </or>
      </applyWhen>
      
      <!-- MKE04 & MKE06 have a BME that can manipulate SRAM_U and a bit-band for SRAM_U as well -->
      <copy source="Project_Settings/Linker_Files/ARMLtd_GCC-rom-mk-sramu.ld"  target="Project_Settings/Linker_Files/Linker-rom.ld" replace="true" />
      <copy source="Project_Settings/Linker_Files/MemoryMap-sramu.ld"          target="Project_Settings/Linker_Files/MemoryMap-$(targetDeviceName).ld"  replace="true" />
      <copy source="Project_Headers/bitband-mke.h"                             target="Project_Headers/bitband.h" />

      <variable id="projectOptionValue.Clock-setup" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="projectOptionValue.UART-setup" name="UART setup code" description="Adds C stdio (UART) support for newlib" >
         <requirement idRef="projectOptionValue.Clock-setup"/>
      </variable>
      
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-MKE0x.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKE0x.h" target="Project_Headers/clock_configure.h" />
      </block>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/uart-mke.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </block>

   </projectActionList>
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKL0xZ4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKL0x -->
   <projectActionList id="Options-file-list-MKL0xZ4">
      <applyWhen>
         <or>
            <deviceSubfamilyIs>MKL02Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL04Z4</deviceSubfamilyIs>
            <deviceSubfamilyIs>MKL05Z4</deviceSubfamilyIs>
         </or>
      </applyWhen>
      <variable id="projectOptionValue.Clock-setup" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="projectOptionValue.UART-setup" name="UART setup code" description="Adds C stdio (UART) support for newlib" >
         <requirement idRef="projectOptionValue.Clock-setup"/>
      </variable>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.Clock-setup" />
         </applyWhen>
         <copy source="Startup_Code/clock-MKL0x.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKL0x.h" target="Project_Headers/clock_configure.h" />
      </block>
      <block>
         <applyWhen>
            <variableRef idRef="projectOptionValue.UART-setup" />
         </applyWhen>
         <copy source="Startup_Code/uart-mkl.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </block>
   </projectActionList>
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.CFVx_DeviceOptions/Options-file-list-CFV2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >

   <!-- Extra Optional files for Coldfire V1 -->
   <projectActionList id="Options-file-list-CFV2" >
      <applyWhen>
         <and>
            <deviceFamilyIs>CFV2</deviceFamilyIs>
            <deviceSubfamilyIs>MCF5225x</deviceSubfamilyIs>
         </and>
      </applyWhen>
      <variable id="Clock-setup-CFV2-mcf5225x" name="Clock setup code"  description="Adds code for basic clock initialization - check assumptions made" />
      <condition variable="Clock-setup-CFV2-mcf5225x" >
         <copy source="Startup_Code/clock-mcf5225x.c"                    target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-mcf5225x.h"       target="Project_Headers/clock_configure.h" />
      </condition>
   </projectActionList>

   <!-- Extra Optional files for Coldfire MCF5223x -->
   <projectActionList id="Options-file-list-CFV2-mcf5223x" >
      <applyWhen>
         <and>
            <deviceFamilyIs>CFV2</deviceFamilyIs>
            <deviceSubfamilyIs>MCF5223x</deviceSubfamilyIs>
         </and>
      </applyWhen>
      <variable id="Clock-setup-CFV2-mcf5223x" name="Clock setup code"   description="Adds code for basic clock initialization - check assumptions made" />
      <condition variable="Clock-setup-CFV2-mcf5223x" >
         <copy source="Startup_Code/clock-mcf5223x.c"                    target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-mcf5223x.h"       target="Project_Headers/clock_configure.h" />
      </condition>
   </projectActionList>

</root>
