=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/package.dtd
<!-- Root fileElement -->
<!ELEMENT root (projectActionList*) >
   <!ATTLIST root version CDATA #REQUIRED >
 
<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList (applyWhen|projectActionList|projectActionListRef|variable|block|excludeSourceFile|excludeSourceFolder|createFolder|copy|projectOption|customAction)*>
   <!ATTLIST projectActionList id    ID     #IMPLIED>
   <!ATTLIST projectActionList root  CDATA  #IMPLIED>

<!-- Condition controlling when list action is applied -->
<!ELEMENT applyWhen (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)>

<!ELEMENT and ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)*) >
<!ELEMENT or  ((and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches)*) >
<!ELEMENT not  (and|or|not|variableRef|deviceNameIs|deviceFamilyIs|deviceSubfamilyIs|deviceNameMatches|deviceFamilyMatches|deviceSubfamilyMatches) >

<!ELEMENT variableRef EMPTY >
   <!ATTLIST variableRef idRef 			CDATA 			#REQUIRED>
   <!ATTLIST variableRef condition 		(isTrue|lessThan|lessThanOrEqual|equal|greaterThan|greaterThanOrEqual) "isTrue">
   <!ATTLIST variableRef defaultValue 	(true|false) 	#IMPLIED>
   <!ATTLIST variableRef value   		CDATA 			#IMPLIED>

<!ELEMENT deviceNameIs (#PCDATA) >
<!ELEMENT deviceFamilyIs (#PCDATA) >
<!ELEMENT deviceSubfamilyIs (#PCDATA) >
<!ELEMENT deviceNameMatches (#PCDATA) >
<!ELEMENT deviceFamilyMatches (#PCDATA) >
<!ELEMENT deviceSubfamilyMatches (#PCDATA) >

<!ELEMENT projectActionListRef EMPTY>
   <!ATTLIST projectActionListRef ref IDREF #REQUIRED>
 
<!-- Variable controlling a block -->
<!ELEMENT variable ((requirement|preclusion)*) >
   <!ATTLIST variable id           CDATA #REQUIRED>
   <!ATTLIST variable name         CDATA #IMPLIED>
   <!ATTLIST variable description  CDATA #IMPLIED>
   <!ATTLIST variable type         (boolean) 	"boolean" >
   <!ATTLIST variable defaultValue (true|false) "false">
   <!ATTLIST variable values       CDATA #IMPLIED>
   
<!ELEMENT requirement EMPTY >
   <!ATTLIST requirement idRef CDATA #REQUIRED>

<!ELEMENT preclusion EMPTY >
   <!ATTLIST preclusion idRef CDATA #REQUIRED>

<!-- Condition controlling actions -->
<!ELEMENT block (applyWhen,(excludeSourceFile|excludeSourceFolder|createFolder|copy|deleteResource|projectOption|customAction)*)>
   <!--ATTLIST block variable    IDREF  #REQUIRED -->
   <!--ATTLIST block negated     (true|false) "false" -->
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    CDATA #REQUIRED>

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source  				CDATA #REQUIRED>
   <!ATTLIST copy target  				CDATA #REQUIRED>
   <!ATTLIST copy type    				CDATA #IMPLIED>
   <!ATTLIST copy macroReplacement  (true|false) "true">
   <!ATTLIST copy replace           (true|false) "false">
   
<!-- Eclipse project options (for gcc, gdb etc) -->
<!ELEMENT projectOption (value*)>
   <!ATTLIST projectOption id        CDATA        #REQUIRED>
   <!ATTLIST projectOption replace   (true|false) "false">

<!-- Custom build action -->
<!ELEMENT customAction (value)* >
   <!ATTLIST customAction class       CDATA #REQUIRED>
   
<!-- Attribute value for projectOption --> 
<!ELEMENT value (#PCDATA)>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/CortexM3-Project-actions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >
   <!-- 
   Cortex-M3 
      NXP-LPC
      STM32
    -->      

   <!-- Base STM32 files -->
   <projectActionList id="STM32F10xx-files" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM3</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM3F</deviceFamilyMatches>
            </or>
            <deviceSubfamilyMatches>^STM32.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <createFolder target="Sources"                         type="" />
      <createFolder target="Startup_Code"                    type="" />
      <createFolder target="Project_Headers"                 type="include" />
      <createFolder target="Project_Settings/Linker_Files"   type="" />
   
      <copy source="Startup_Code/system-stm32f10x.c"                          target="Startup_Code/system.c" />
      <copy source="Startup_Code/vectors-stm32.c"                             target="Startup_Code/vectors.c" />
      <copy source="Startup_Code/newlib_stubs.c"                              target="Startup_Code/newlib_stubs.c" />
      <copy source="Startup_Code/startup_ARMLtdGCC_CortexM3.S"                target="Startup_Code/startup_ARMLtdGCC.S" />
      <copy source="Project_Settings/Debug.launch"                            target="Project_Settings/$(projectName)-Debug.launch" />
      <copy source="Project_Settings/Linker_Files/ARMLtd_GCC-rom-stm32.ld"    target="Project_Settings/Linker_Files/Linker-rom.ld" />
      <copy source="Project_Settings/Linker_Files/MemoryMap.ld"               target="Project_Settings/Linker_Files/MemoryMap-$(targetDeviceName).ld" />
      <copy source="Project_Headers/derivative-STM32xx.h"                     target="Project_Headers/derivative.h" />
      <copy source="Project_Headers/stm32f10x.h"                              target="Project_Headers/stm32f10x.h" />
      <copy source="Project_Headers/system_stm32f10x.h"                       target="Project_Headers/system_stm32f10x.h" />
      <copy source="Project_Headers/core_cm3.h"                               target="Project_Headers/core_cm3.h" />
      <copy source="Project_Headers/core_cmFunc.h"                            target="Project_Headers/core_cmFunc.h" />
      <copy source="Project_Headers/core_cmInstr.h"                           target="Project_Headers/core_cmInstr.h" />
      <copy source="Project_Headers/utilities-stm32.h"                        target="Project_Headers/utilities.h" />
      <copy source="Sources/main-stm32.c"                                     target="Sources/main.c" />
   
      <copy source="$(externalVectorTable)"                                   target="Startup_Code/vectors.c" replace="true" />
      <copy source="$(externalLinkerScript)"                                  target="Project_Settings/Linker_Files/Custom.ld" />
      <copy source="$(externalHeaderFile)"                                    target="Project_Headers/$(targetDevice).h" replace="true" />
      <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.preprocessor.def.symbols" >
         <value>STM32F10X_LD</value>
      </projectOption>            
      <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.preprocessor.def.symbols" >
         <value>STM32F10X_LD</value>
      </projectOption>            
   </projectActionList>

   <!-- Base NXP-LPC files -->
   <projectActionList id="NXP-LPC-file-list" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM3</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM3F</deviceFamilyMatches>
            </or>
            <deviceSubfamilyMatches>^LPC\d+.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <createFolder target="Sources"                         type="" />
      <createFolder target="Startup_Code"                    type="" />
      <createFolder target="Project_Headers"                 type="include" />
      <createFolder target="Project_Settings/Linker_Files"   type="" />
   
      <copy source="Startup_Code/system-lpc.c"                                target="Startup_Code/system.c" />
      <copy source="Startup_Code/vectors-lpc.c"                               target="Startup_Code/vectors.c" />
      <copy source="Startup_Code/newlib_stubs.c"                              target="Startup_Code/newlib_stubs.c" />
      <copy source="Startup_Code/startup_ARMLtdGCC_CortexM3.S"                target="Startup_Code/startup_ARMLtdGCC.S" />
      <copy source="Project_Settings/Debug.launch"                            target="Project_Settings/$(projectName)-Debug.launch" />
      <copy source="Project_Settings/Linker_Files/ARMLtd_GCC-rom-lpc.ld"      target="Project_Settings/Linker_Files/ARMLtd_GCC-rom.ld" />
      <copy source="Project_Settings/Linker_Files/MemoryMap.ld"               target="Project_Settings/Linker_Files/MemoryMap-$(targetDeviceName).ld" />
      <copy source="Project_Headers/derivative.h"                             target="Project_Headers/derivative.h" />
      <copy source="Project_Headers/TargetDevice.h"                           target="Project_Headers/$(targetDevice).h" />
      <copy source="Project_Headers/core_cm3.h"                               target="Project_Headers/core_cm3.h" />
      <copy source="Project_Headers/core_cmFunc.h"                            target="Project_Headers/core_cmFunc.h" />
      <copy source="Project_Headers/core_cmInstr.h"                           target="Project_Headers/core_cmInstr.h" />
   
      <copy source="$(externalVectorTable)"                                   target="Startup_Code/vectors.c" replace="true" />
      <copy source="$(externalLinkerScript)"                                  target="Project_Settings/Linker_Files/Custom.ld" />
      <copy source="$(externalHeaderFile)"                                    target="Project_Headers/$(targetDevice).h" replace="true" />
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/010.BaseProject/gnuSettings.mcf52xxx.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- GNU Build options CFVx -->
   <projectActionList id="gnuSettings.mcf52xxx" root="usbdm_resource_path/Stationery/CFVx/">
      <applyWhen>
         <deviceFamilyIs>CFV2</deviceFamilyIs>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.toolchain.c.linker.linkerFile">
         <value>$(linkerFile)</value>
      </projectOption>
      <projectOption id="net.sourceforge.usbdm.cdt.toolchain.cpp.linker.linkerFile">
         <value>$(linkerFile)</value>
      </projectOption>
      <projectOption id="gnu.c.link.option.paths">
         <value>&quot;${ProjDirPath}/Project_Settings/Linker_Files&quot;</value>
      </projectOption>
      <projectOption id="gnu.cpp.link.option.paths">
         <value>&quot;${ProjDirPath}/Project_Settings/Linker_Files&quot;</value>
      </projectOption>
   </projectActionList>
   
   <projectActionList id="gnuSettings.mcf52213">
      <applyWhen>
         <deviceNameIs>MCF52213</deviceNameIs>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu" > 
         <value>net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu.52213</value> 
      </projectOption>
   </projectActionList>

   <projectActionList id="gnuSettings.mcf52223">
      <applyWhen>
         <or>
            <deviceNameIs>MCF52221</deviceNameIs>
            <deviceNameIs>MCF52223</deviceNameIs>
         </or>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu" > 
      <value>net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu.52223</value> 
      </projectOption> 
   </projectActionList>

   <projectActionList id="gnuSettings.mcf5223x">
      <applyWhen>
         <or>
            <deviceNameIs>MCF52230</deviceNameIs>
            <deviceNameIs>MCF52231</deviceNameIs>
            <deviceNameIs>MCF52232</deviceNameIs>
            <deviceNameIs>MCF52233</deviceNameIs>
            <deviceNameIs>MCF52234</deviceNameIs>
            <deviceNameIs>MCF52235</deviceNameIs>
            <deviceNameIs>MCF52236</deviceNameIs>
         </or>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu" > 
         <value>net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu.52235</value> 
      </projectOption> 
   </projectActionList>

   <projectActionList id="gnuSettings.mcf52259">
      <applyWhen>
         <or>
            <deviceNameIs>MCF52259</deviceNameIs>
            <deviceNameMatches>.*52259.*</deviceNameMatches>
         </or>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu" > 
         <value>net.sourceforge.usbdm.cdt.coldfire.toolchain.mcpu.52259</value> 
      </projectOption>
   </projectActionList>

   
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/CortexM4-Project-actions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >

   <!-- Base MK files -->
   <projectActionList id="Kinetis-MK-files" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <deviceSubfamilyMatches>^MK\d+.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <createFolder target="Sources"                         type="" />
      <createFolder target="Startup_Code"                    type="" />
      <createFolder target="Project_Headers"                 type="include" />
      <createFolder target="Project_Settings/Linker_Files"   type="" />
   
      <copy source="Startup_Code/system-mk.c"                                 target="Startup_Code/system.c" />
      <copy source="Startup_Code/vectors-mk.c"                                target="Startup_Code/vectors.c" />
      <copy source="Startup_Code/newlib_stubs.c"                              target="Startup_Code/newlib_stubs.c" />

      <copy source="Startup_Code/startup_ARMLtdGCC_CortexM4.S"                target="Startup_Code/startup_ARMLtdGCC.S" />

      <copy source="Project_Settings/Debug.launch"                            target="Project_Settings/$(projectName)-Debug.launch" />

      <copy source="Project_Settings/Linker_Files/ARMLtd_GCC-rom-mk-sramu.ld" target="Project_Settings/Linker_Files/Linker-rom.ld" replace="true" />
      <copy source="Project_Settings/Linker_Files/MemoryMap-sramu.ld"         target="Project_Settings/Linker_Files/MemoryMap-$(targetDeviceName).ld"  replace="true" />

      <copy source="Project_Headers/bitband-mk.h"                             target="Project_Headers/bitband.h" />
      <copy source="Project_Headers/derivative.h"                             target="Project_Headers/derivative.h" />
      <copy source="Project_Headers/TargetDevice.h"                           target="Project_Headers/$(targetDevice).h" />
      <copy source="Project_Headers/system.h"                                 target="Project_Headers/system.h" />
      <copy source="Project_Headers/core_cm4.h"                               target="Project_Headers/core_cm4.h" />
      <copy source="Project_Headers/core_cm4_simd.h"                          target="Project_Headers/core_cm4_simd.h" />
      <copy source="Project_Headers/core_cmFunc.h"                            target="Project_Headers/core_cmFunc.h" />
      <copy source="Project_Headers/core_cmInstr.h"                           target="Project_Headers/core_cmInstr.h" />
      <copy source="Project_Headers/utilities-mk.h"                           target="Project_Headers/utilities.h" />

      <copy source="Sources/main.c"                                           target="Sources/main.c" />
   
      <copy source="$(externalVectorTable)"                                   target="Startup_Code/vectors.c" replace="true" />
      <copy source="$(externalLinkerScript)"                                  target="Project_Settings/Linker_Files/Custom.ld" />
      <copy source="$(externalHeaderFile)"                                    target="Project_Headers/$(targetDevice).h" replace="true" />
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/150.ARM_Boards/FRDM-Blinky.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >

   <!-- Blinky example for Freedom board -->
   <projectActionList id="FRDM-Blinky-MK" >
      <applyWhen>
         <and>
            <or>
               <deviceFamilyMatches>CortexM4</deviceFamilyMatches>
               <deviceFamilyMatches>CortexM4F</deviceFamilyMatches>
            </or>
            <or>
               <deviceNameMatches>^FRDM-.*</deviceNameMatches>
               <deviceNameMatches>^TWR-.*</deviceNameMatches>
            </or>
         </and>
      </applyWhen>
      <variable id="projectOptionValue.FRDM-Blinky" name="Blinky example" description="Add Blinky Example code for Freedom board" />
      <block>
         <applyWhen >
            <variableRef idRef="projectOptionValue.FRDM-Blinky" />
         </applyWhen>
         <copy source="Project_Headers/leds.h"        target="Project_Headers/leds.h" />
         <copy source="Project_Headers/Board_LEDs.h"  target="Project_Headers/Board_LEDs.h" />
         <copy source="Sources/leds.c"                target="Sources/leds.c" />
         <copy source="Sources/main.c"                target="Sources/main.c" replace="true" />
      </block>
   </projectActionList>

   <!-- Blinky example for Freedom board -->
   <projectActionList id="FRDM-Blinky-MKL" >
      <applyWhen>
         <and>
            <deviceNameMatches>^FRDM-.*</deviceNameMatches>
            <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
            <deviceSubfamilyMatches>^MKL\d+.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <variable id="projectOptionValue.FRDM-Blinky" name="Blinky example" description="Add Blinky Example code for Freedom board" />
      <block>
         <applyWhen >
            <variableRef idRef="projectOptionValue.FRDM-Blinky" />
         </applyWhen>
         <copy source="Project_Headers/leds.h"        target="Project_Headers/leds.h" />
         <copy source="Project_Headers/Board_LEDs.h"  target="Project_Headers/Board_LEDs.h" />
         <copy source="Sources/leds.c"                target="Sources/leds.c" />
         <copy source="Sources/main.c"                target="Sources/main.c" replace="true" />
      </block>
   </projectActionList>

   <!-- Blinky example for Freedom board -->
   <projectActionList id="FRDM-Blinky-MKE" >
      <applyWhen>
         <and>
            <deviceNameMatches>^FRDM-.*</deviceNameMatches>
            <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
            <deviceSubfamilyMatches>^MKE\d+.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <variable id="projectOptionValue.FRDM-Blinky" name="Blinky example" description="Add Blinky Example code for Freedom board" />
      <block>
         <applyWhen >
            <variableRef idRef="projectOptionValue.FRDM-Blinky" />
         </applyWhen>
         <copy source="Project_Headers/leds.h"        target="Project_Headers/leds.h" />
         <copy source="Project_Headers/Board_LEDs.h"  target="Project_Headers/Board_LEDs.h" />
         <copy source="Sources/leds-mke.c"            target="Sources/leds.c" />
         <copy source="Sources/main.c"                target="Sources/main.c" replace="true" />
      </block>
   </projectActionList>

   <!-- Blinky example for Freedom board -->
   <projectActionList id="FRDM-Blinky-MKM" >
      <applyWhen>
         <and>
            <deviceNameMatches>^FRDM-.*</deviceNameMatches>
            <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
            <deviceSubfamilyMatches>^MKM\d+.*</deviceSubfamilyMatches>
         </and>
      </applyWhen>
      <variable id="projectOptionValue.FRDM-Blinky" name="Blinky example" description="Add Blinky Example code for Freedom board" />
      <block>
         <applyWhen >
            <variableRef idRef="projectOptionValue.FRDM-Blinky" />
         </applyWhen>
         <copy source="Project_Headers/leds.h"        target="Project_Headers/leds.h" />
         <copy source="Project_Headers/Board_LEDs.h"  target="Project_Headers/Board_LEDs.h" />
         <copy source="Sources/leds-mkm.c"            target="Sources/leds.c" />
         <copy source="Sources/main.c"                target="Sources/main.c" replace="true" />
      </block>
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Cortex-Project-actions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0" >

   <!-- Cortex-M0,M3,M4 -->    
   <projectActionList id="Cortex-Project-actions" >
      <applyWhen>
         <and>
            <deviceFamilyMatches>CortexM0</deviceFamilyMatches>
         </and>
      </applyWhen>
      <!--  Not sufficient RAM for standard-C library initialisation (newlib mostly) -->
      <variable id="linkerRamSize"   />
      <variable id="linkerFlashSize" />
      <block>
         <applyWhen>
            <variableRef idRef="linkerRamSize" condition="lessThanOrEqual" value="2048" />
         </applyWhen>
         <projectOption id="gnu.cpp.link.option.nostart">
            <value>true</value>
         </projectOption>
         <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.preprocessor.def.symbols">
            <value>__NO_STARTFILES__</value>
         </projectOption>
         <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.preprocessor.def.symbols">
            <value>__NO_STARTFILES__</value>
         </projectOption>
      </block>
   </projectActionList>
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/100.ARM_DeviceOptions/Options-file-list-MKxxM10.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Extra Optional files for MKxxM10 -->
   <projectActionList id="Options-file-list-MKxxM10">
      <applyWhen>
         <or>
            <deviceSubfamilyIs>MK10D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK20D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK30D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK40D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK50D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK51D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK52D10</deviceSubfamilyIs>
            <deviceSubfamilyIs>MK53D10</deviceSubfamilyIs>
         </or>
      </applyWhen>
      <variable id="Clock-setup-MKxxM10" name="Clock setup code" description="Adds code for basic clock initialization - check assumptions made" />
      <variable id="UART-setup-MKxxM10" name="UART setup code" description="Adds C stdio (UART) support for newlib" />
      <condition variable="Clock-setup-MKxxM10">
         <copy source="Startup_Code/clock-MKxx.c" target="Startup_Code/clock.c" />
         <copy source="Project_Headers/clock_configure-MKxxM10.h" target="Project_Headers/clock_configure.h" />
      </condition>
      <condition variable="UART-setup-MKxxM10">
         <copy source="Startup_Code/uart-mk.c" target="Startup_Code/uart.c" />
         <copy source="Project_Headers/uart.h" target="Project_Headers/uart.h" />
      </condition>
   </projectActionList>

</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/500.STM32_SPL/STM32-spl-files.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- Additions for STM32xx SPL -->
   <projectActionList id="STM32-spl-files" >
      <applyWhen>
         <deviceSubfamilyIs>STM32</deviceSubfamilyIs>
      </applyWhen>
      <variable id="STM32-spl" name="Standard Peripheral Library"
         description="Adds code for the STM32 Standard peripheral Library - check assumptions made" />
      <condition variable="STM32-spl">
         <createFolder target="spl" type="include" />
         <copy source="../spl/Release_Notes.html" target="SPL.html" type="link" />
         <copy source="../spl/inc" target="spl/inc" />
         <copy source="../spl/src" target="spl/src" />
         <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.include.paths">
            <value>&quot;${ProjDirPath}/spl/inc&quot;</value>
            <value>&quot;${ProjDirPath}/spl/src&quot;</value>
         </projectOption>
         <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.include.paths">
            <value>&quot;${ProjDirPath}/spl/inc&quot;</value>
            <value>&quot;${ProjDirPath}/spl/src&quot;</value>
         </projectOption>
         <projectOption id="net.sourceforge.usbdm.gnu.cpp.compiler.option.preprocessor.def.symbols">
            <value>USE_STDPERIPH_DRIVER</value>
         </projectOption>
         <projectOption id="net.sourceforge.usbdm.gnu.c.compiler.option.preprocessor.def.symbols">
            <value>USE_STDPERIPH_DRIVER</value>
         </projectOption>
      </condition>
   </projectActionList>
</root>

=== Gibbon1/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/010.BaseProject/gnuSettings.cortex.m0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE root SYSTEM "../package.dtd">

<root version="1.0">
   <!-- GNU Build options Cortex M0 (e.g. MKL, MKE) devices -->
   <projectActionList id="gnuSettings.cortex.m0">
      <applyWhen>
         <deviceFamilyIs>CortexM0</deviceFamilyIs>
      </applyWhen>
      <projectOption id="net.sourceforge.usbdm.cdt.arm.toolchain.mcpu">
         <value>net.sourceforge.usbdm.cdt.arm.toolchain.mcpu.cortexM0</value>
      </projectOption>
      <projectOption id="net.sourceforge.usbdm.cdt.arm.toolchain.mthumb">
         <value>true</value>
      </projectOption>
      <projectOption id="net.sourceforge.usbdm.cdt.arm.toolchain.buildtools">
         <value>$(buildToolId)</value>
      </projectOption>
      <projectOption id="net.sourceforge.usbdm.cdt.toolchain.c.linker.linkerFile">
         <value>$(linkerFile)</value>
      </projectOption>
      <projectOption id="net.sourceforge.usbdm.cdt.toolchain.cpp.linker.linkerFile">
         <value>$(linkerFile)</value>
      </projectOption>
      <projectOption id="gnu.c.link.option.paths">
         <value>&quot;${ProjDirPath}/Project_Settings/Linker_Files&quot;</value>
      </projectOption>
      <projectOption id="gnu.cpp.link.option.paths">
         <value>&quot;${ProjDirPath}/Project_Settings/Linker_Files&quot;</value>
      </projectOption>
   </projectActionList>
</root>
